server:
  port: 8080


spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_manager_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  token:
    secret: the-secret-for-harvesting-from-existence-the-greatest-fruitfulness-and-the-greatest-enjoyment-is-to-live-dangerously
    expired: 3600000