server:
  port: 8081


spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 0
        spring:
          json:
            add:
              type:
                headers: false
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/task_manager_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
jwt:
  token:
    secret: the-secret-for-harvesting-from-existence-the-greatest-fruitfulness-and-the-greatest-enjoyment-is-to-live-dangerously
    expired: 36000000
topic: test
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE